"""In-code knowledge base. Edit this text and re-run: python -m src.ingest"""

DOCUMENTS = {
    "HR_Policy": [
        "Company: Anthrasync Private Limited. Working Hours. Standard working hours are 9:00 AM to 6:00 PM, Monday to Friday, with a one-hour lunch break. Employees complete 40 working hours per week. Flexible start times between 8:00 AM and 10:00 AM are permitted with manager approval. Remote Work Policy. Employees can work from home on Wednesdays and Fridays with manager approval. Fully remote arrangements require approval from the department head and HR. Remote employees must remain reachable during core hours of 11:00 AM to 4:00 PM.",
        "Leave Policy. All full-time employees are eligible for 24 paid leaves annually, credited at the start of each calendar year, used for vacation, personal, or casual purposes. A maximum of 10 unused paid leaves may be carried forward; any excess will lapse. Employees also receive 12 days of sick leave per year. Sick leave exceeding two consecutive days requires a medical certificate. Maternity leave is 26 weeks and paternity leave is 2 weeks. Anthrasync observes 12 public holidays each calendar year.",
        "Notice Period. Confirmed employees must serve a notice period of 60 days upon resignation. The notice period may be reduced or waived at the discretion of the reporting manager and HR. A formal handover must be completed before the last working day. Performance reviews are conducted twice a year, in June and December.",
    ],
    "Customer_FAQ": [
        "Orders and Shipping. Standard delivery takes 5 to 7 business days. Express delivery takes 2 to 3 business days. Orders placed after 4:00 PM are processed the next business day. A tracking link is emailed once your order ships, and order status is visible under My Orders in your account dashboard.",
        "Refunds and Returns. What is the refund policy? Customers can request a full refund within 30 days of purchase if they face technical issues, provided the item is unused and in its original packaging. Refunds are processed to the original payment method within 7 to 10 business days after the returned item is received. Digital products, gift cards, and personalized items are non-refundable unless defective.",
        "Account and Billing. How do I reset my password? Click Forgot Password on the login page and follow the emailed instructions; the reset link is valid for 30 minutes. Customer support is available Monday to Saturday, 9:00 AM to 8:00 PM, via live chat and email at support@anthrasync.com, with average response time under 4 hours. Hardware products carry a 12-month limited warranty.",
    ],
    "Product_Documentation": [
        "Overview. DataSync Pro is Anthrasync enterprise data integration platform. It connects to over 200 data sources, transforms data through a visual pipeline builder, and loads it into the destination of your choice. Features include incremental sync, built-in scheduling, role-based access control, full audit logging, and a real-time monitoring dashboard with email and Slack alerting.",
        "Editions and System Requirements. Three editions: Starter (up to 5 pipelines, 1 million rows per month), Growth (up to 50 pipelines, 50 million rows per month), and Enterprise (unlimited pipelines, dedicated support, 99.9% uptime SLA). The self-hosted version requires a Linux server with at least 8 GB RAM, 4 CPU cores, 50 GB disk, and Docker 20.10 or later.",
        "Data Retention. Pipeline run logs are retained for 90 days on the Starter and Growth editions and 365 days on the Enterprise edition. Sync history beyond the retention window is archived and can be restored on request. Supported sources include PostgreSQL, MySQL, SQL Server, MongoDB, Snowflake, BigQuery, Redshift, Salesforce, and HubSpot.",
    ],
    "Technical_Guide": [
        "Installation (Self-Hosted). Pull the official Docker image and start the stack using docker compose up -d. The application is available on port 8080 by default, and configuration is read from the .env file. On first launch, complete the setup wizard to create an administrator account and set the encryption key (at least 32 characters, not changeable after setup).",
        "API Authentication and Rate Limits. The REST API uses bearer-token authentication. Generate an API token from Settings, API Tokens, and include it in the Authorization header. Tokens expire after 90 days unless renewed. The API allows 100 requests per minute per token on the Growth edition and 1,000 on the Enterprise edition; exceeding the limit returns an HTTP 429 response.",
        "Emergency Contact and IT Support. For server failure or urgent IT support, contact the DevOps team at support@anthrasync.com. The DevOps on-call engineer responds to critical P1 incidents within 2 hours, including outside business hours. Non-urgent issues should be raised through the helpdesk portal.",
    ],
    "Compliance_Guidelines": [
        "Data Classification and Password Policy. Company data is classified as Public, Internal, Confidential, or Restricted. Confidential and Restricted data must be encrypted in transit and at rest. Passwords must be at least 12 characters and include uppercase, lowercase, numbers, and symbols. Passwords must be changed every 90 days, and the previous five passwords may not be reused. Multi-factor authentication is mandatory for systems handling Confidential or Restricted data.",
        "Data Retention and Incident Reporting. Customer personal data is permanently removed within 30 days of a verified deletion request; backups are purged within an additional 60 days. Any suspected security incident or data breach must be reported to security@anthrasync.com within one hour of discovery. Affected parties are notified as required by law within 72 hours.",
        "Acceptable Use and Vendors. Company devices and accounts are for business purposes. Installing unauthorized software, disabling security controls, or sharing credentials is prohibited. Vendors that process company data must sign a data processing agreement and pass a security review before onboarding; vendor access is reviewed quarterly.",
    ],
    "Process_Document": [
        "Expense Reimbursement and Onboarding. Submit your expense report through the finance portal within 30 days of incurring the expense, with itemized receipts. Claims are approved by your reporting manager and processed by finance, paid with the next payroll cycle. Expenses above 25,000 require prior written approval. New hires complete mandatory security and compliance training within the first week.",
        "Procurement and IT Support. Purchase requests are raised through the procurement portal: up to 50,000 approved by the department head, above 50,000 require finance approval, above 500,000 require leadership approval. IT issues are prioritized as P1 (critical, 2-hour response), P2 (high, same business day), or P3 (standard, 2 business days).",
    ],
}
